image: soseth/debian-ci-base:stretch

build:
  stage: build
  script:
    - gbp buildpackage --git-debian-branch=$CI_COMMIT_REF_NAME -b -us -uc
  artifacts:
    name: packets
    expire_in: 3 months
    paths:
      - ../*.deb
