name: E2E
on: [push, pull_request]
jobs:
  goversion:
    uses: ./.github/workflows/go-version.yaml
  test:
    runs-on: ubuntu-latest
    needs: goversion
    strategy:
      fail-fast: true
      matrix:
        target:
        - linux-amd64-e2e
        - linux-386-e2e
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: ${{ needs.goversion.outputs.goversion }}
    - run: date
    - env:
        TARGET: ${{ matrix.target }}
      run: |
        set -euo pipefail

        echo "${TARGET}"
        case "${TARGET}" in
          linux-amd64-e2e)
            PASSES='build release e2e' MANUAL_VER=v3.4.7 CPU='4' EXPECT_DEBUG='true' COVER='false' RACE='true' ./test.sh
            ;;
          linux-386-e2e)
            GOARCH=386 PASSES='build e2e' CPU='4' EXPECT_DEBUG='true' COVER='false' RACE='true' ./test.sh
            ;;
          *)
            echo "Failed to find target"
            exit 1
            ;;
        esac
