name: grpcProxy-tests
on: [push, pull_request]
jobs:
  goversion:
    uses: ./.github/workflows/go-version.yaml
  test:
    runs-on: ubuntu-latest
    needs: goversion
    strategy:
      fail-fast: true
      matrix:
        target:
        - linux-amd64-grpcproxy
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: ${{ needs.goversion.outputs.goversion }}
    - run: date
    - env:
        TARGET: ${{ matrix.target }}
      run: |
        set -euo pipefail

        echo "${TARGET}"
        case "${TARGET}" in
          linux-amd64-grpcproxy)
            PASSES='build grpcproxy'  CPU='4' COVER='false' RACE='true' ./test.sh
            ;;
          *)
            echo "Failed to find target"
            exit 1
            ;;
        esac
